# Generated by Django 4.2.4 on 2023-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='insert a phone e-mail', max_length=254),
        ),
    ]
