# Generated by Django 4.2.4 on 2023-08-17 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_food', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='insert a name', max_length=100)),
                ('description', models.TextField(default='insert a description', max_length=1000)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='assets')),
            ],
        ),
    ]
