# Generated by Django 4.2.5 on 2023-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='short_description',
            field=models.TextField(default='insert a description', max_length=1000),
        ),
    ]
